hugo_env: &hugo_env
  BASE_URL: https://github.com/GaelGSST/restaurant-landingpage

kind: pipeline
type: docker
name: hugo-website

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: debug-variables
    image: alpine:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
    commands:
      - echo "=== Debug Variables ==="
      - echo "AWS_ACCESS_KEY_ID is set: $${AWS_ACCESS_KEY_ID:+YES}"
      - echo "AWS_SECRET_ACCESS_KEY is set: $${AWS_SECRET_ACCESS_KEY:+YES}"
      - echo "AWS_SESSION_TOKEN is set: $${AWS_SESSION_TOKEN:+YES}"
      - echo "Files to upload:"
      - ls -la public/ || echo "public/ directory not found"

  - name: upload-to-s3
    image: plugins/s3
    settings:
      bucket: drone-bucket-s3-restaurant
      region: us-east-1
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      session_token:
        from_secret: aws_session_token
      source: public/**
      target: /
      acl: public-read
      strip_prefix: public
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
