hugo_env: &hugo_env
  BASE_URL: https://github.com/GaelGSST/restaurant-landingpage

kind: pipeline
type: docker
name: hugo-website

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: upload-to-s3
    image: plugins/s3
    settings:
      bucket: drone-bucket-s3-restaurant
      region: us-east-1
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      source: public/**
      target: /
      acl: public-read
      strip_prefix: public
