hugo_env: &hugo_env
  BASE_URL: http://drone-bucket-s3-restaurant.s3-website-us-east-1.amazonaws.com

kind: pipeline
type: docker
name: hugo-website

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: create-release-archive
    image: alpine:latest
    commands:
      - apk add --no-cache tar gzip
      - export RELEASE_VERSION=${DRONE_BUILD_NUMBER:-$(date +%Y%m%d-%H%M%S)}
      - export ARCHIVE_NAME="restaurant-website-release-$RELEASE_VERSION.tar.gz"
      - tar -czf $ARCHIVE_NAME -C public .
      - echo "Created archive: $ARCHIVE_NAME"

  - name: upload-release-to-s3
    image: amazon/aws-cli:2.13.7
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - export RELEASE_VERSION=${DRONE_BUILD_NUMBER:-$(date +%Y%m%d-%H%M%S)}
      - export ARCHIVE_NAME="restaurant-website-release-$RELEASE_VERSION.tar.gz"
      - aws s3 cp $ARCHIVE_NAME drone-bucket-s3-restaurant-realease/$ARCHIVE_NAME
      - echo "Uploaded release archive to S3: $ARCHIVE_NAME"
